Repository SHDS-ESC/Sol-Food, pull requests merged in 2025-06, with the labels that each got.

#3 프로젝트 기본 설정
  .gitignore
  pom.xml
  src/main/java/solfood/configuration/DbProperties.java
  src/main/java/solfood/configuration/Interceptor.java
  src/main/java/solfood/configuration/MvcConfig.java
  src/main/resources/log4j.xml
  src/main/resources/log4jdbc.log4j2.properties
  src/main/webapp/WEB-INF/web.xml
Labels: 세팅

#7 Jiwon/user/login/social login
  .gitignore
  .idea/jsLibraryMappings.xml
  sol-food.iml
  src/main/java/configuration/DbProperties.java
  src/main/java/configuration/KakaoProperties.java
  src/main/java/configuration/MvcConfig.java
  src/main/java/configuration/ServerProperties.java
  src/main/java/kr/co/solfood/user/login/LoginController.java
  src/main/java/kr/co/solfood/user/login/LoginMapper.java
  src/main/java/kr/co/solfood/user/login/LoginService.java
  src/main/java/kr/co/solfood/user/login/LoginServiceImpl.java
  src/main/java/kr/co/solfood/user/login/LoginVO.java
  src/main/java/kr/co/solfood/user/mypage/MypageController.java
  src/main/java/solfood/configuration/Interceptor.java
  src/main/java/util/LoginInterceptor.java
  src/main/resources/kr/co/solfood/user/login/LoginMapper.xml
  src/main/webapp/WEB-INF/views/user/add-register.jsp
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/WEB-INF/views/user/mypage.jsp
  src/main/webapp/WEB-INF/web.xml
Labels: 추가기능

#20 Gahee/user/login/native login
  .idea/jsLibraryMappings.xml
  pom.xml
  src/main/java/configuration/MvcConfig.java
  src/main/java/kr/co/solfood/user/login/CompanyVO.java
  src/main/java/kr/co/solfood/user/login/DepartmentVO.java
  src/main/java/kr/co/solfood/user/login/LoginController.java
  src/main/java/kr/co/solfood/user/login/LoginMapper.java
  src/main/java/kr/co/solfood/user/login/LoginRequest.java
  src/main/java/kr/co/solfood/user/login/LoginService.java
  src/main/java/kr/co/solfood/user/login/LoginServiceImpl.java
  src/main/java/kr/co/solfood/user/login/LoginVO.java
  src/main/resources/kr/co/solfood/user/login/LoginMapper.xml
  src/main/webapp/WEB-INF/views/user/add-register.jsp
  src/main/webapp/WEB-INF/views/user/join.jsp
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/WEB-INF/views/user/search-id.jsp
  src/main/webapp/WEB-INF/views/user/search-pwd.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/error/404.jsp
Labels: 추가기능

#33 카테고리 경로 수정
  src/main/java/kr/co/solfood/user/store/StoreController.java
  src/main/webapp/WEB-INF/views/user/store.jsp
Labels: 개선

#46 README.md 기초 세팅
  README.md
Labels: 문서

#61 더보기 기능 구현
  src/main/java/kr/co/solfood/user/store/StoreController.java
  src/main/java/kr/co/solfood/user/store/StoreMapper.java
  src/main/java/kr/co/solfood/user/store/StoreService.java
  src/main/java/kr/co/solfood/user/store/StoreServiceImpl.java
  src/main/java/kr/co/solfood/user/store/StoreVO.java
  src/main/java/kr/co/solfood/util/PageDTO.java
  src/main/java/kr/co/solfood/util/PageMaker.java
  src/main/resources/kr/co/solfood/user/store/StoreMapper.xml
  src/main/webapp/WEB-INF/views/user/store.jsp
  src/main/webapp/css/store.css
  src/main/webapp/js/store.js
Labels: 추가기능

#58 페이징 공통 유틸 클래스 개발, 점주 관리 페이지 검색 기능 개선 (페이징 위주)
  .idea/jsLibraryMappings.xml
  .idea/modules.xml
  .idea/webContexts.xml
  pom.xml
  sol-food.iml
  src/main/java/kr/co/solfood/admin/dto/ChartRequestDTO.java
  src/main/java/kr/co/solfood/admin/dto/OwnerSearchDTO.java
  src/main/java/kr/co/solfood/admin/dto/OwnerSearchResponseDTO.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeController.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeService.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeServiceImpl.java
  src/main/java/kr/co/solfood/admin/home/AdminMapper.java
  src/main/java/kr/co/solfood/admin/home/AdminSearchVO.java
  src/main/java/kr/co/solfood/util/PageDTO.java
  src/main/java/kr/co/solfood/util/PageMaker.java
  src/main/resources/kr/co/solfood/admin/home/AdminMapper.xml
  src/main/webapp/WEB-INF/views/admin/owner-management/home.jsp
  src/main/webapp/WEB-INF/views/admin/user-management/home.jsp
  src/test/java/kr/co/solfood/admin/AdminTest.java
Labels: 개선, 추가기능

#62 AWS 인터셉터 추가와 store 기능 병합
  src/main/java/config/MvcConfig.java
  src/main/java/kr/co/solfood/common/s3/FileUploadController.java
  src/main/java/kr/co/solfood/common/s3/FileUploadSessionInterceptor.java
  src/main/java/kr/co/solfood/common/s3/S3ServiceV2.java
  src/main/java/kr/co/solfood/user/store/StoreController.java
  src/main/java/kr/co/solfood/user/store/StoreMapper.java
  src/main/java/kr/co/solfood/user/store/StoreService.java
  src/main/java/kr/co/solfood/user/store/StoreServiceImpl.java
  src/main/resources/kr/co/solfood/user/store/StoreMapper.xml
  src/main/webapp/WEB-INF/views/user/store.jsp
  src/main/webapp/css/store.css
  src/main/webapp/js/store.js
  src/test/java/kr/co/solfood/user/review/ReviewServiceImplTest.java
Labels: 개선

#66 Category 설정 로직 개선 및 파일 구조 개선
  src/main/java/config/MvcConfig.java
  src/main/java/configuration/MvcConfig.java
  src/main/java/kr/co/solfood/admin/crawler/StoreWebCrawler.java
  src/main/java/kr/co/solfood/common/s3/FileUploadController.java
  src/main/java/kr/co/solfood/common/s3/FileUploadSessionInterceptor.java
  src/main/java/kr/co/solfood/common/s3/RateLimitService.java
  src/main/java/kr/co/solfood/common/s3/S3ServiceV2.java
  src/main/java/kr/co/solfood/user/category/CategoryMapper.java
  src/main/java/kr/co/solfood/user/category/CategoryService.java
  src/main/java/kr/co/solfood/user/category/CategoryServiceImpl.java
  src/main/java/kr/co/solfood/user/category/CategoryVO.java
  src/main/java/kr/co/solfood/user/login/LoginController.java
  src/main/java/kr/co/solfood/user/login/LoginServiceImpl.java
  src/main/java/kr/co/solfood/user/login/UserLoginInterceptor.java
  src/main/java/kr/co/solfood/user/mypage/MypageController.java
  src/main/java/kr/co/solfood/user/mypage/MypageServiceImpl.java
  src/main/java/kr/co/solfood/user/review/ReviewConstants.java
  src/main/java/kr/co/solfood/user/review/ReviewController.java
  src/main/java/kr/co/solfood/user/review/ReviewMapper.java
  src/main/java/kr/co/solfood/user/review/ReviewService.java
  src/main/java/kr/co/solfood/user/review/ReviewServiceImpl.java
  src/main/java/kr/co/solfood/user/review/ReviewVO.java
  src/main/java/kr/co/solfood/user/review/ReviewValidator.java
  src/main/java/kr/co/solfood/user/store/CategoryProperties.java
  src/main/java/kr/co/solfood/user/store/StoreController.java
  src/main/java/kr/co/solfood/user/store/StoreServiceImpl.java
  src/main/java/kr/co/solfood/user/store/StoreVO.java
  src/main/resources/kr/co/solfood/user/category/CategoryMapper.xml
  src/main/resources/kr/co/solfood/user/review/ReviewMapper.xml
  src/main/resources/kr/co/solfood/user/store/StoreMapper.xml
  src/main/webapp/WEB-INF/views/owner/home.jsp
  src/main/webapp/WEB-INF/views/review/list.jsp
  src/main/webapp/WEB-INF/views/review/reviewWrite.jsp
  src/main/webapp/WEB-INF/views/user/review/edit.jsp
  src/main/webapp/WEB-INF/views/user/review/write.jsp
  src/main/webapp/WEB-INF/views/user/store.jsp
  src/main/webapp/WEB-INF/views/user/store/detail.jsp
  src/main/webapp/WEB-INF/views/user/store/list.jsp
  src/main/webapp/WEB-INF/views/user/userControl/extra.jsp
  src/main/webapp/WEB-INF/views/user/userControl/find-pwd.jsp
  src/main/webapp/WEB-INF/views/user/userControl/info.jsp
  src/main/webapp/WEB-INF/views/user/userControl/login.jsp
  src/main/webapp/WEB-INF/views/user/userControl/mypage.jsp
  src/main/webapp/WEB-INF/views/user/userControl/register.jsp
  src/main/webapp/WEB-INF/views/user/userControl/search-id.jsp
  src/main/webapp/WEB-INF/views/user/userControl/search-pwd.jsp
  src/main/webapp/css/review.css
  src/main/webapp/css/storedetail.css
  src/main/webapp/error/404.jsp
  src/main/webapp/index.jsp
  src/main/webapp/js/review.js
  src/main/webapp/js/store.js
  src/main/webapp/js/storedetail.js
Labels: 개선, 세팅

#75 review 개선점(1)
  README.md
  src/main/java/config/PropertiesConfig.java
  src/main/java/kr/co/solfood/admin/crawler/StoreWebCrawler.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeController.java
  src/main/java/kr/co/solfood/common/s3/FileUploadController.java
  src/main/java/kr/co/solfood/common/s3/S3ServiceV2.java
  src/main/java/kr/co/solfood/user/category/CategoryService.java
  src/main/java/kr/co/solfood/user/category/CategoryServiceImpl.java
  src/main/java/kr/co/solfood/user/review/ReviewConstants.java
  src/main/java/kr/co/solfood/user/review/ReviewController.java
  src/main/java/kr/co/solfood/user/review/ReviewService.java
  src/main/java/kr/co/solfood/user/review/ReviewVO.java
  src/main/java/kr/co/solfood/user/review/ReviewValidator.java
  src/main/java/kr/co/solfood/user/store/CategoryProperties.java
  src/main/java/kr/co/solfood/user/store/StoreController.java
  src/main/java/kr/co/solfood/user/store/response/CategoryResponseVO.java
  src/main/java/kr/co/solfood/user/store/response/StoreListResponseVO.java
  src/main/java/kr/co/solfood/user/store/response/StoreSearchResponseVO.java
Labels: 개선

#69 찜 추가 기능 및 마이페이지 찜 목록 조회 기능 추가
  src/main/java/kr/co/solfood/user/like/LikeController.java
  src/main/java/kr/co/solfood/user/like/LikeMapper.java
  src/main/java/kr/co/solfood/user/like/LikeService.java
  src/main/java/kr/co/solfood/user/like/LikeServiceImpl.java
  src/main/java/kr/co/solfood/user/like/LikeVO.java
  src/main/java/kr/co/solfood/user/mypage/MypageController.java
  src/main/java/kr/co/solfood/user/mypage/MypageMapper.java
  src/main/java/kr/co/solfood/user/mypage/MypageService.java
  src/main/java/kr/co/solfood/user/mypage/MypageServiceImpl.java
  src/main/java/kr/co/solfood/user/store/StoreController.java
  src/main/java/kr/co/solfood/user/store/StoreMapper.java
  src/main/java/kr/co/solfood/user/store/StoreService.java
  src/main/java/kr/co/solfood/user/store/StoreServiceImpl.java
  src/main/resources/kr/co/solfood/user/like/LikeMapper.xml
  src/main/resources/kr/co/solfood/user/mypage/MypageMapper.xml
  src/main/resources/kr/co/solfood/user/store/StoreMapper.xml
  src/main/webapp/WEB-INF/views/user/login/like.jsp
  src/main/webapp/WEB-INF/views/user/login/mypage.jsp
  src/main/webapp/WEB-INF/views/user/store.jsp
  src/main/webapp/WEB-INF/views/user/store/list.jsp
  src/main/webapp/css/mypage.css
  src/main/webapp/css/store.css
  src/main/webapp/js/like.js
  src/main/webapp/js/mypage.js
  src/main/webapp/js/store.js
  src/test/java/kr/co/solfood/user/like/LikeServiceImplTest.java
  src/test/java/kr/co/solfood/user/review/ReviewServiceImplTest.java
Labels: 개선, 추가기능

#68 어드민 > 점주 페이지 완성
  src/main/java/config/MvcConfig.java
  src/main/java/kr/co/solfood/admin/dto/OwnerSearchResponseDTO.java
  src/main/java/kr/co/solfood/admin/dto/OwnerStatusUpdateDTO.java
  src/main/java/kr/co/solfood/admin/dto/PaymentSearchRequestDTO.java
  src/main/java/kr/co/solfood/admin/dto/PaymentSearchResponseDTO.java
  src/main/java/kr/co/solfood/admin/dto/ResolvationSearchRequestDTO.java
  src/main/java/kr/co/solfood/admin/dto/ResolvationSearchResponseDTO.java
  src/main/java/kr/co/solfood/admin/dto/UserSearchRequestDTO.java
  src/main/java/kr/co/solfood/admin/dto/UserSearchResponseDTO.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeController.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeService.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeServiceImpl.java
  src/main/java/kr/co/solfood/admin/home/AdminMapper.java
  src/main/java/kr/co/solfood/admin/login/AdminLoginController.java
  src/main/java/kr/co/solfood/admin/login/AdminLoginInterceptor.java
  src/main/java/kr/co/solfood/admin/login/AdminLoginMapper.java
  src/main/java/kr/co/solfood/admin/login/AdminLoginService.java
  src/main/java/kr/co/solfood/admin/login/AdminLoginServiceImpl.java
  src/main/java/kr/co/solfood/admin/login/OwnerLoginController.java
  src/main/java/kr/co/solfood/admin/login/OwnerLoginInterceptor.java
  src/main/java/kr/co/solfood/admin/login/OwnerVO.java
  src/main/resources/kr/co/solfood/admin/home/AdminMapper.xml
  src/main/resources/kr/co/solfood/admin/login/AdminLoginMapper.xml
  src/main/webapp/WEB-INF/views/admin/home.jsp
  src/main/webapp/WEB-INF/views/admin/login.jsp
  src/main/webapp/WEB-INF/views/admin/owner-management/home.jsp
  src/main/webapp/WEB-INF/views/admin/payment-management/home.jsp
  src/main/webapp/WEB-INF/views/admin/user-management/home.jsp
  src/test/java/kr/co/solfood/admin/AdminTest.java
Labels: 개선

#72 운영자 페이지 리팩터링
  pom.xml
  src/main/java/kr/co/solfood/admin/dto/ChartRequestDTO.java
  src/main/java/kr/co/solfood/admin/dto/OwnerSearchResponseDTO.java
  src/main/java/kr/co/solfood/admin/dto/OwnerStatusUpdateDTO.java
  src/main/java/kr/co/solfood/admin/dto/SelectChartData.java
  src/main/java/kr/co/solfood/admin/dto/UserSearchRequestDTO.java
  src/main/java/kr/co/solfood/admin/dto/UserSearchResponseDTO.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeController.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeServiceImpl.java
  src/main/java/kr/co/solfood/admin/login/AdminLoginController.java
  src/main/java/kr/co/solfood/util/ErrorCode.java
  src/main/resources/kr/co/solfood/admin/home/AdminMapper.xml
  src/main/resources/kr/co/solfood/user/login/LoginMapper.xml
  src/main/webapp/WEB-INF/views/admin/home.jsp
  src/main/webapp/WEB-INF/views/admin/login.jsp
  src/main/webapp/WEB-INF/views/admin/owner-management/home.jsp
  src/main/webapp/WEB-INF/views/admin/payment-management/home.jsp
  src/main/webapp/WEB-INF/views/admin/user-management/home.jsp
  src/main/webapp/css/admin/admin-login.css
  src/main/webapp/css/admin/owner-management.css
  src/main/webapp/css/admin/payment-management.css
  src/main/webapp/css/admin/user-management.css
  src/main/webapp/js/admin/owner-management.js
  src/main/webapp/js/admin/payment-management.js
  src/main/webapp/js/admin/user-management.js
  src/test/java/kr/co/solfood/admin/AdminTest.java
  src/test/java/kr/co/solfood/admin/home/AdminHomeControllerTest.java
  src/test/java/kr/co/solfood/admin/home/AdminHomeServiceTest.java
  src/test/java/kr/co/solfood/admin/home/AdminMapperTest.java
  src/test/java/kr/co/solfood/admin/login/AdminLoginMapperTest.java
  src/test/java/kr/co/solfood/admin/login/AdminLoginServiceImplTest.java
  src/test/java/kr/co/solfood/user/login/ExceptionTest.java
Labels: 개선

#86 지점 자세히 보기 페이지 및 상점 상태 변경
  src/main/java/kr/co/solfood/admin/dto/OwnerSearchResponseDTO.java
  src/main/java/kr/co/solfood/admin/dto/OwnerStatusUpdateDTO.java
  src/main/java/kr/co/solfood/admin/dto/StoreStatusUpdateDTO.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeController.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeService.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeServiceImpl.java
  src/main/java/kr/co/solfood/admin/home/AdminMapper.java
  src/main/resources/kr/co/solfood/admin/home/AdminMapper.xml
  src/main/webapp/WEB-INF/views/admin/owner-management/detail.jsp
  src/main/webapp/WEB-INF/views/admin/owner-management/home.jsp
  src/main/webapp/css/admin/owner-detail.css
  src/main/webapp/css/admin/owner-management.css
  src/main/webapp/js/admin/owner-detail.js
  src/main/webapp/js/admin/owner-management.js
  src/test/java/kr/co/solfood/admin/home/AdminHomeControllerTest.java
  src/test/java/kr/co/solfood/admin/home/AdminHomeServiceTest.java
  src/test/java/kr/co/solfood/admin/home/AdminMapperTest.java
Labels: 개선, 추가기능
