Repository SHDS-ESC/Sol-Food, pull requests merged in 2025-07, with the labels that each got.

#47 Gahee/owner/login/native login
  src/main/java/config/MvcConfig.java
  src/main/java/kr/co/solfood/common/s3/FileUploadSessionInterceptor.java
  src/main/java/kr/co/solfood/owner/login/OwnerLoginController.java
  src/main/java/kr/co/solfood/owner/login/OwnerLoginInterceptor.java
  src/main/java/kr/co/solfood/owner/login/OwnerLoginMapper.java
  src/main/java/kr/co/solfood/owner/login/OwnerLoginService.java
  src/main/java/kr/co/solfood/owner/login/OwnerLoginServiceImpl.java
  src/main/java/kr/co/solfood/owner/login/OwnerVO.java
  src/main/java/kr/co/solfood/owner/menu/OwnerMenuController.java
  src/main/java/kr/co/solfood/owner/menu/OwnerMenuMapper.java
  src/main/java/kr/co/solfood/owner/menu/OwnerMenuService.java
  src/main/java/kr/co/solfood/owner/menu/OwnerMenuServiceImpl.java
  src/main/java/kr/co/solfood/owner/menu/OwnerMenuVO.java
  src/main/java/kr/co/solfood/owner/store/OwnerCategoryVO.java
  src/main/java/kr/co/solfood/owner/store/OwnerStoreController.java
  src/main/java/kr/co/solfood/owner/store/OwnerStoreMapper.java
  src/main/java/kr/co/solfood/owner/store/OwnerStoreService.java
  src/main/java/kr/co/solfood/owner/store/OwnerStoreServiceImpl.java
  src/main/java/kr/co/solfood/owner/store/OwnerStoreVO.java
  src/main/java/kr/co/solfood/user/login/DepartmentVO.java
  src/main/java/kr/co/solfood/user/login/LoginController.java
  src/main/java/kr/co/solfood/user/mypage/MypageController.java
  src/main/resources/kr/co/solfood/owner/login/OwnerLoginMapper.xml
  src/main/resources/kr/co/solfood/owner/menu/OwnerMenuMapper.xml
  src/main/resources/kr/co/solfood/owner/store/OwnerStoreMapper.xml
  src/main/webapp/WEB-INF/views/owner/addMenu.jsp
  src/main/webapp/WEB-INF/views/owner/addStore.jsp
  src/main/webapp/WEB-INF/views/owner/editMenu.jsp
  src/main/webapp/WEB-INF/views/owner/editStore.jsp
  src/main/webapp/WEB-INF/views/owner/extra.jsp
  src/main/webapp/WEB-INF/views/owner/login.jsp
  src/main/webapp/WEB-INF/views/owner/menu.jsp
  src/main/webapp/WEB-INF/views/owner/register.jsp
  src/main/webapp/WEB-INF/views/owner/review.jsp
  src/main/webapp/WEB-INF/views/owner/sales.jsp
  src/main/webapp/WEB-INF/views/owner/store.jsp
  src/main/webapp/WEB-INF/views/owner/temp.jsp
  src/main/webapp/WEB-INF/views/user/login/find-pwd.jsp
  src/test/java/kr/co/solfood/user/login/LoginServiceImplTest.java
Labels: 추가기능

#98 Admin -> Develop (애널리틱스, 경로 변경 이슈 처리)
  .gitignore
  pom.xml
  src/main/java/config/GoogleAnalyticsConfig.java
  src/main/java/kr/co/solfood/admin/dto/DailyUsersDto.java
  src/main/java/kr/co/solfood/admin/dto/OwnerSearchResponseDTO.java
  src/main/java/kr/co/solfood/admin/dto/ReportRowDto.java
  src/main/java/kr/co/solfood/admin/dto/UserSearchResponseDTO.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeController.java
  src/main/java/kr/co/solfood/admin/home/AnalyticsService.java
  src/main/java/kr/co/solfood/user/login/UserLoginInterceptor.java
  src/main/java/kr/co/solfood/user/login/UserVO.java
  src/main/resources/kr/co/solfood/admin/home/AdminMapper.xml
  src/main/resources/kr/co/solfood/user/login/LoginMapper.xml
  src/main/webapp/WEB-INF/views/admin/home.jsp
  src/main/webapp/WEB-INF/views/admin/owner-management/detail.jsp
  src/main/webapp/WEB-INF/views/admin/owner-management/home.jsp
  src/main/webapp/WEB-INF/views/admin/payment-management/home.jsp
  src/main/webapp/WEB-INF/views/admin/user-management/home.jsp
  src/main/webapp/css/admin/owner-management.css
  src/main/webapp/index.jsp
  src/main/webapp/js/admin/owner-detail.js
  src/main/webapp/js/admin/owner-management.js
  src/main/webapp/js/admin/user-management.js
  src/test/java/kr/co/solfood/admin/home/AdminHomeControllerTest.java
Labels: 개선, 버그, 추가기능

#82 Feat: 룰렛 뽑기 게임 초안
  src/main/java/kr/co/solfood/user/game/GameController.java
  src/main/webapp/WEB-INF/views/user/game/roulette.jsp
  src/main/webapp/css/game/roulette.css
  src/main/webapp/js/game/roulette.js
Labels: 개선, 추가기능

#103 Owner
  .gitignore
  src/main/java/config/GoogleAnalyticsConfig.java
  src/main/java/config/MvcConfig.java
  src/main/java/kr/co/solfood/admin/login/OwnerLoginController.java
  src/main/java/kr/co/solfood/admin/login/OwnerVO.java
  src/main/java/kr/co/solfood/common/s3/FileUploadSessionInterceptor.java
  src/main/java/kr/co/solfood/owner/login/OwnerLoginController.java
  src/main/java/kr/co/solfood/owner/login/OwnerLoginInterceptor.java
  src/main/java/kr/co/solfood/owner/login/OwnerLoginMapper.java
  src/main/java/kr/co/solfood/owner/login/OwnerLoginService.java
  src/main/java/kr/co/solfood/owner/login/OwnerLoginServiceImpl.java
  src/main/java/kr/co/solfood/owner/login/OwnerVO.java
  src/main/java/kr/co/solfood/owner/menu/OwnerMenuController.java
  src/main/java/kr/co/solfood/owner/menu/OwnerMenuMapper.java
  src/main/java/kr/co/solfood/owner/menu/OwnerMenuService.java
  src/main/java/kr/co/solfood/owner/menu/OwnerMenuServiceImpl.java
  src/main/java/kr/co/solfood/owner/menu/OwnerMenuVO.java
  src/main/java/kr/co/solfood/owner/store/OwnerCategoryVO.java
  src/main/java/kr/co/solfood/owner/store/OwnerStoreController.java
  src/main/java/kr/co/solfood/owner/store/OwnerStoreMapper.java
  src/main/java/kr/co/solfood/owner/store/OwnerStoreService.java
  src/main/java/kr/co/solfood/owner/store/OwnerStoreServiceImpl.java
  src/main/java/kr/co/solfood/owner/store/OwnerStoreVO.java
  src/main/java/kr/co/solfood/user/login/DepartmentVO.java
  src/main/java/kr/co/solfood/user/login/LoginController.java
  src/main/java/kr/co/solfood/user/mypage/MypageController.java
  src/main/resources/kr/co/solfood/owner/login/OwnerLoginMapper.xml
  src/main/resources/kr/co/solfood/owner/menu/OwnerMenuMapper.xml
  src/main/resources/kr/co/solfood/owner/store/OwnerStoreMapper.xml
  src/main/webapp/WEB-INF/views/owner/addMenu.jsp
  src/main/webapp/WEB-INF/views/owner/addStore.jsp
  src/main/webapp/WEB-INF/views/owner/editMenu.jsp
  src/main/webapp/WEB-INF/views/owner/editStore.jsp
  src/main/webapp/WEB-INF/views/owner/extra.jsp
  src/main/webapp/WEB-INF/views/owner/login.jsp
  src/main/webapp/WEB-INF/views/owner/menu.jsp
  src/main/webapp/WEB-INF/views/owner/register.jsp
  src/main/webapp/WEB-INF/views/owner/review.jsp
  src/main/webapp/WEB-INF/views/owner/sales.jsp
  src/main/webapp/WEB-INF/views/owner/store.jsp
  src/main/webapp/WEB-INF/views/owner/temp.jsp
  src/main/webapp/WEB-INF/views/user/login/find-pwd.jsp
  src/test/java/kr/co/solfood/user/login/LoginServiceImplTest.java
Labels: 추가기능

#102 가게 정렬 기능 추가
  src/main/java/kr/co/solfood/user/store/StoreController.java
  src/main/java/kr/co/solfood/user/store/StoreMapper.java
  src/main/java/kr/co/solfood/user/store/StoreService.java
  src/main/java/kr/co/solfood/user/store/StoreServiceImpl.java
  src/main/resources/kr/co/solfood/user/store/StoreMapper.xml
  src/main/webapp/WEB-INF/views/user/store/list.jsp
  src/main/webapp/css/store.css
  src/main/webapp/js/store.js
Labels: 추가기능

#107 Store 지도, 상세정보 개선 및 장바구니 개선
  src/main/java/kr/co/solfood/owner/menu/OwnerMenuVO.java
  src/main/java/kr/co/solfood/user/menu/MenuVO.java
  src/main/resources/kr/co/solfood/owner/menu/OwnerMenuMapper.xml
  src/main/webapp/WEB-INF/views/owner/addMenu.jsp
  src/main/webapp/WEB-INF/views/owner/editMenu.jsp
  src/main/webapp/WEB-INF/views/owner/menu.jsp
  src/main/webapp/WEB-INF/views/user/cart/cart.jsp
  src/main/webapp/WEB-INF/views/user/store/detail.jsp
  src/main/webapp/css/storedetail.css
  src/main/webapp/js/cart.js
  src/main/webapp/js/store.js
  src/main/webapp/js/storedetail.js
  src/main/webapp/js/urlConstants.js
Labels: 개선

#108 사용자 정지/해제
  src/main/java/kr/co/solfood/admin/dto/UserSearchResponseDTO.java
  src/main/java/kr/co/solfood/admin/dto/UserStatusUpdateDTO.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeController.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeService.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeServiceImpl.java
  src/main/java/kr/co/solfood/admin/home/AdminMapper.java
  src/main/java/kr/co/solfood/admin/login/AdminLoginInterceptor.java
  src/main/java/kr/co/solfood/user/login/UserLoginInterceptor.java
  src/main/java/kr/co/solfood/user/login/UserStatus.java
  src/main/resources/kr/co/solfood/admin/home/AdminMapper.xml
  src/main/webapp/WEB-INF/views/admin/home.jsp
  src/main/webapp/WEB-INF/views/admin/user-management/home.jsp
  src/main/webapp/css/admin/user-management.css
  src/main/webapp/js/admin/owner-management.js
  src/main/webapp/js/admin/user-management.js
Labels: 개선, 버그, 추가기능

#109 결제 초안
  .idea/jarRepositories.xml
  pom.xml
  src/main/java/config/MvcConfig.java
  src/main/java/kr/co/solfood/common/constants/UrlConstants.java
  src/main/java/kr/co/solfood/payments/charge/ChargeController.java
  src/main/java/kr/co/solfood/payments/charge/ChargeMapper.java
  src/main/java/kr/co/solfood/payments/charge/ChargeService.java
  src/main/java/kr/co/solfood/payments/charge/ChargeServiceImpl.java
  src/main/java/kr/co/solfood/payments/charge/ChargeVO.java
  src/main/java/kr/co/solfood/payments/common/CommonPaymentMapper.java
  src/main/java/kr/co/solfood/payments/common/CommonPaymentService.java
  src/main/java/kr/co/solfood/payments/common/CommonPaymentServiceImpl.java
  src/main/java/kr/co/solfood/payments/common/CommonPaymentVO.java
  src/main/java/kr/co/solfood/payments/integrated/IntegratedPaymentMapper.java
  src/main/java/kr/co/solfood/payments/integrated/IntegratedPaymentService.java
  src/main/java/kr/co/solfood/payments/integrated/IntegratedPaymentServiceImpl.java
  src/main/java/kr/co/solfood/payments/integrated/IntegratedPaymentVO.java
  src/main/java/kr/co/solfood/payments/payment/PaymentController.java
  src/main/java/kr/co/solfood/payments/payment/PaymentMapper.java
  src/main/java/kr/co/solfood/payments/payment/PaymentService.java
  src/main/java/kr/co/solfood/payments/payment/PaymentServiceImpl.java
  src/main/java/kr/co/solfood/payments/payment/PaymentVO.java
  src/main/java/kr/co/solfood/user/cart/BillDTO.java
  src/main/java/kr/co/solfood/user/cart/CartController.java
  src/main/java/kr/co/solfood/user/cart/CartItemVO.java
  src/main/java/kr/co/solfood/user/cart/CartService.java
  src/main/java/kr/co/solfood/user/cart/CartServiceImpl.java
  src/main/java/kr/co/solfood/user/login/LoginMapper.java
  src/main/java/kr/co/solfood/user/login/LoginService.java
  src/main/java/kr/co/solfood/user/login/LoginServiceImpl.java
  src/main/java/kr/co/solfood/user/mypage/MypageController.java
  src/main/java/kr/co/solfood/user/store/StoreController.java
  src/main/java/kr/co/solfood/util/CustomExceptionHandler.java
  src/main/java/kr/co/solfood/util/ErrorCode.java
  src/main/java/util/PaymentModelAdvice.java
  src/main/resources/kr/co/solfood/payments/charge/ChargeMapper.xml
  src/main/resources/kr/co/solfood/payments/integrated/IntegratedPaymentMapper.xml
  src/main/resources/kr/co/solfood/payments/payment/PaymentMapper.xml
  src/main/resources/kr/co/solfood/user/login/LoginMapper.xml
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/common/payment-header.jsp
  src/main/webapp/WEB-INF/views/user/cart/make-bill.jsp
  src/main/webapp/WEB-INF/views/user/cart/payment-complete.jsp
  src/main/webapp/WEB-INF/views/user/cart/payment-method.jsp
  src/main/webapp/WEB-INF/views/user/cart/waiting-approval.jsp
  src/main/webapp/WEB-INF/views/user/login/mypage.jsp
  src/main/webapp/WEB-INF/views/user/mypage/charge-history.jsp
  src/main/webapp/WEB-INF/views/user/mypage/charge.jsp
  src/main/webapp/WEB-INF/views/user/mypage/payment-history.jsp
  src/main/webapp/index.jsp
  src/main/webapp/js/cart.js
  src/main/webapp/js/dutch-pay.js
  src/main/webapp/js/invite-friends-lite.js
  src/main/webapp/js/make-bill.js
  src/main/webapp/js/payment-method.js
  src/main/webapp/js/waiting-approval.js
  src/main/webapp/resources/css/mypage.css
  src/main/webapp/resources/js/payment.js
Labels: 추가기능

#125 main페이지, 가게 목록 페이지
  .gitignore
  src/main/java/config/MvcConfig.java
  src/main/java/kr/co/solfood/user/store/StoreController.java
  src/main/java/kr/co/solfood/user/store/StoreMapper.java
  src/main/java/kr/co/solfood/user/store/StoreService.java
  src/main/java/kr/co/solfood/user/store/StoreServiceImpl.java
  src/main/resources/kr/co/solfood/user/store/StoreMapper.xml
  src/main/webapp/WEB-INF/views/user/login/like.jsp
  src/main/webapp/WEB-INF/views/user/login/mypage.jsp
  src/main/webapp/WEB-INF/views/user/store/list.jsp
  src/main/webapp/css/index.css
  src/main/webapp/css/like.css
  src/main/webapp/css/list.css
  src/main/webapp/css/mypage.css
  src/main/webapp/index.jsp
  src/main/webapp/js/index.js
  src/main/webapp/js/store.js
Labels: 디자인

#131 메인페이지, 찜목록, 가게목록페이지 수정
  src/main/resources/kr/co/solfood/user/store/StoreMapper.xml
  src/main/webapp/WEB-INF/views/user/include/header.jsp
  src/main/webapp/WEB-INF/views/user/login/like.jsp
  src/main/webapp/WEB-INF/views/user/store/list.jsp
  src/main/webapp/css/header.css
  src/main/webapp/css/index.css
  src/main/webapp/css/like.css
  src/main/webapp/css/list.css
  src/main/webapp/css/style.css
  src/main/webapp/img/event1.jpg
  src/main/webapp/img/event2.jpg
  src/main/webapp/img/logo-dark.png
  src/main/webapp/img/logo.jpg
  src/main/webapp/img/logo.png
  src/main/webapp/img/logo2.png
  src/main/webapp/index.jsp
  src/main/webapp/js/header.js
  src/main/webapp/js/index.js
  src/main/webapp/js/store.js
Labels: 디자인

#133 Gahee/develop/front -> develop
  src/main/java/kr/co/solfood/user/board/BoardController.java
  src/main/java/kr/co/solfood/user/board/BoardMapper.java
  src/main/java/kr/co/solfood/user/board/BoardService.java
  src/main/java/kr/co/solfood/user/board/BoardServiceImpl.java
  src/main/java/kr/co/solfood/user/board/BoardVO.java
  src/main/java/kr/co/solfood/user/board/response/BoardListResponseVO.java
  src/main/java/kr/co/solfood/user/comment/CommentController.java
  src/main/java/kr/co/solfood/user/comment/CommentMapper.java
  src/main/java/kr/co/solfood/user/comment/CommentService.java
  src/main/java/kr/co/solfood/user/comment/CommentServiceImpl.java
  src/main/java/kr/co/solfood/user/comment/CommentVO.java
  src/main/java/kr/co/solfood/user/login/LoginController.java
  src/main/java/kr/co/solfood/user/mypage/MypageController.java
  src/main/resources/kr/co/solfood/user/board/BoardMapper.xml
  src/main/resources/kr/co/solfood/user/comment/CommentMapper.xml
  src/main/resources/kr/co/solfood/user/login/LoginMapper.xml
  src/main/webapp/WEB-INF/views/user/board/add.jsp
  src/main/webapp/WEB-INF/views/user/board/detail.jsp
  src/main/webapp/WEB-INF/views/user/board/edit.jsp
  src/main/webapp/WEB-INF/views/user/board/list.jsp
  src/main/webapp/WEB-INF/views/user/login/loginpage.jsp
  src/main/webapp/WEB-INF/views/user/mypage/non-user-mypage.jsp
  src/main/webapp/css/board/board-list.css
  src/main/webapp/css/mypage/non-user-mypage.css
  src/main/webapp/css/style.css
  src/main/webapp/img/kakao_login_medium_wide.png
Labels: 디자인, 개선, 추가기능

#130 결제 구현 - 같이 결제 내 발의자 결제
  src/main/java/config/MvcConfig.java
  src/main/java/kr/co/solfood/common/constants/UrlConstants.java
  src/main/java/kr/co/solfood/payments/integrated/IntegratedPaymentMapper.java
  src/main/java/kr/co/solfood/payments/integrated/IntegratedPaymentService.java
  src/main/java/kr/co/solfood/payments/integrated/IntegratedPaymentServiceImpl.java
  src/main/java/kr/co/solfood/payments/payment/PaymentController.java
  src/main/java/kr/co/solfood/payments/payment/PaymentMapper.java
  src/main/java/kr/co/solfood/payments/payment/PaymentService.java
  src/main/java/kr/co/solfood/payments/payment/PaymentServiceImpl.java
  src/main/java/kr/co/solfood/user/cart/BillDTO.java
  src/main/java/kr/co/solfood/user/cart/CartConstants.java
  src/main/java/kr/co/solfood/user/cart/CartController.java
  src/main/java/kr/co/solfood/user/cart/CartScheduler.java
  src/main/java/kr/co/solfood/user/cart/CartSessionListener.java
  src/main/java/kr/co/solfood/user/cart/CartVO.java
  src/main/java/kr/co/solfood/user/login/LoginMapper.java
  src/main/java/kr/co/solfood/user/login/LoginService.java
  src/main/java/kr/co/solfood/user/login/LoginServiceImpl.java
  src/main/java/kr/co/solfood/util/ApplicationContextProvider.java
  src/main/resources/kr/co/solfood/payments/integrated/IntegratedPaymentMapper.xml
  src/main/resources/kr/co/solfood/payments/payment/PaymentMapper.xml
  src/main/resources/kr/co/solfood/user/login/LoginMapper.xml
  src/main/webapp/WEB-INF/views/user/cart/invite-friends.jsp
  src/main/webapp/WEB-INF/views/user/cart/make-bill.jsp
  src/main/webapp/WEB-INF/views/user/cart/payment-method.jsp
  src/main/webapp/WEB-INF/views/user/cart/waiting-approval.jsp
  src/main/webapp/WEB-INF/views/user/mypage/charge.jsp
  src/main/webapp/WEB-INF/views/user/store/detail.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/css/make-bill.css
  src/main/webapp/js/cart.js
  src/main/webapp/js/charge.js
  src/main/webapp/js/invite-friends-lite.js
  src/main/webapp/js/make-bill.js
  src/main/webapp/js/payment-method.js
  src/main/webapp/js/storedetail.js
  src/main/webapp/js/urlConstants.js
  src/main/webapp/js/waiting-approval.js
Labels: 개선, 추가기능

#136 결제 페이지 필터링 구현
  src/main/java/kr/co/solfood/admin/dto/PaymentSearchRequestDTO.java
  src/main/java/kr/co/solfood/admin/dto/PaymentSearchRequestDto.java
  src/main/java/kr/co/solfood/admin/dto/PaymentSearchResponseDTO.java
  src/main/java/kr/co/solfood/admin/dto/PaymentSearchResponseDto.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeController.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeService.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeServiceImpl.java
  src/main/java/kr/co/solfood/admin/home/AdminMapper.java
  src/main/resources/kr/co/solfood/admin/home/AdminMapper.xml
  src/main/webapp/WEB-INF/views/admin/payment-management/home.jsp
  src/main/webapp/css/admin/payment-management.css
  src/main/webapp/js/admin/payment-management.js
Labels: 개선, 추가기능

#138 Feat: 결제 테이블 통합, 자세히 보기 구현, 리드미 수정
  README.md
  src/main/java/kr/co/solfood/admin/dto/PaymentDistinctRequestDto.java
  src/main/java/kr/co/solfood/admin/dto/PaymentDistinctResponseDto.java
  src/main/java/kr/co/solfood/admin/dto/PaymentSearchResponseDto.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeController.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeService.java
  src/main/java/kr/co/solfood/admin/home/AdminHomeServiceImpl.java
  src/main/java/kr/co/solfood/admin/home/AdminMapper.java
  src/main/resources/kr/co/solfood/admin/home/AdminMapper.xml
  src/main/webapp/WEB-INF/views/admin/payment-management/detail.jsp
  src/main/webapp/WEB-INF/views/admin/payment-management/home.jsp
  src/main/webapp/css/admin/payment-management.css
  src/main/webapp/js/admin/payment-management.js
Labels: 개선, 추가기능

#139 Sunwoo/user/store/front -> develop
  src/main/webapp/WEB-INF/views/user/include/backbtn-header.jsp
  src/main/webapp/WEB-INF/views/user/include/header.jsp
  src/main/webapp/WEB-INF/views/user/mypage/charge-history.jsp
  src/main/webapp/WEB-INF/views/user/mypage/charge.jsp
  src/main/webapp/WEB-INF/views/user/mypage/payment-history.jsp
  src/main/webapp/WEB-INF/views/user/store/list.jsp
  src/main/webapp/css/storedetail.css
  src/main/webapp/img/event2.jpg
  src/main/webapp/img/event3.jpg
  src/main/webapp/img/event4.jpg
  src/main/webapp/index.jsp
  src/main/webapp/js/index.js
Labels: 디자인

#140 feat : 더보기 버튼
  src/main/webapp/WEB-INF/views/user/board/list.jsp
Labels: 추가기능
